model_name: xdxd_spacenet4

model_path:
train: true
infer: false

pretrained: true
nn_framework:  torch
batch_size: 2

data_specs:
  width: 512
  height:  512
  image_type: zscore
  rescale: false
  rescale_minima: auto
  rescale_maxima: auto
  channels: 3
  label_type: mask
  is_categorical: false
  mask_channels: 1
  val_holdout_frac: 0.4
  data_workers:
  dtype:

training_data_csv: '/home/sarah/solaris_cowc/cowc/datasets/ground_truth_sets/toronto.csv'
validation_data_csv:
inference_data_csv: '/home/sarah/solaris_cowc/cowc/datasets/ground_truth_sets/test_data_cowc2.csv'

training_augmentation:
  augmentations:
    HorizontalFlip:
      p: 0.5
    RandomRotate90:
      p: 0.5
    RandomCrop:
      height: 512
      width: 512
      p: 1.0
    Normalize:
      mean:
        - 0.4838757527165056
        - 0.4812117968328578
        - 0.4387958322833492
      std:
        - 0.142897272820752
        - 0.13639378850861264
        - 0.13438871891934998
      max_pixel_value: 255.0
      p: 1.0
  p: 1.0
  shuffle: true
validation_augmentation:
  augmentations:
    CenterCrop:
      height: 512
      width: 512
      p: 1.0
    Normalize:
      mean:
        - 0.4838757527165056
        - 0.4812117968328578
        - 0.4387958322833492
      std:
        - 0.142897272820752
        - 0.13639378850861264
        - 0.13438871891934998
      max_pixel_value: 255.0
      p: 1.0
  p: 1.0
inference_augmentation:
  augmentations:
    Normalize:
      mean:
        - 0.4838757527165056
        - 0.4812117968328578
        - 0.4387958322833492
      std:
        - 0.142897272820752
        - 0.13639378850861264
        - 0.13438871891934998
      max_pixel_value: 255.0
      p: 1.0
  p: 1.0
training:
  epochs:  60
  steps_per_epoch:
  optimizer: Adam
  lr: 1e-4
  opt_args:
  loss:
    bcewithlogits:
    jaccard:
  loss_weights:
    bcewithlogits: 10
    jaccard: 2.5
  metrics:
    training:
    validation:
  checkpoint_frequency: 10
  callbacks:
    model_checkpoint:
      filepath: '/home/sarah/solaris_cowc/xdxd_best.pth'
      monitor: val_loss
  model_dest_path: '/home/sarah/solaris_cowc/xdxd.pth'
  verbose: true

inference:
  window_step_size_x:
  window_step_size_y:
  output_dir: '/home/sarah/solaris_cowc/inference_out/'
